{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastflow
subjects:
- kind: ServiceAccount
  name: fastflow
roleRef:
  kind: Role
  name: fastflow
  apiGroup: rbac.authorization.k8s.io
{{- end }}
